/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ActivationGuideRouteImport } from './routes/activation-guide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as OrderSuccessIdRouteImport } from './routes/order-success.$id'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as ApiPublicEdfapayWebhookRouteImport } from './routes/api/public/edfapay-webhook'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin/admin.reviews'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin.reports'
import { Route as AdminAdminProfileRouteImport } from './routes/_admin/admin.profile'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminInventoryRouteImport } from './routes/_admin/admin.inventory'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin/admin.customers'
import { Route as AdminAdminCouponsRouteImport } from './routes/_admin/admin.coupons'
import { Route as AdminAdminArticlesRouteImport } from './routes/_admin/admin.articles'
import { Route as AdminAdminActivationGuideRouteImport } from './routes/_admin/admin.activation-guide'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAccountOrderIdRouteImport } from './routes/_authenticated/account.order.$id'
import { Route as AdminAdminAccountingReportsRouteImport } from './routes/_admin/admin.accounting.reports'
import { Route as AdminAdminAccountingPeriodsRouteImport } from './routes/_admin/admin.accounting.periods'
import { Route as AdminAdminAccountingExpensesRouteImport } from './routes/_admin/admin.accounting.expenses'
import { Route as AdminAdminAccountingCostsRouteImport } from './routes/_admin/admin.accounting.costs'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationGuideRoute = ActivationGuideRouteImport.update({
  id: '/activation-guide',
  path: '/activation-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessIdRoute = OrderSuccessIdRouteImport.update({
  id: '/order-success/$id',
  path: '/order-success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const ApiPublicEdfapayWebhookRoute = ApiPublicEdfapayWebhookRouteImport.update({
  id: '/api/public/edfapay-webhook',
  path: '/api/public/edfapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProfileRoute = AdminAdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminInventoryRoute = AdminAdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCouponsRoute = AdminAdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminArticlesRoute = AdminAdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminActivationGuideRoute =
  AdminAdminActivationGuideRouteImport.update({
    id: '/admin/activation-guide',
    path: '/admin/activation-guide',
    getParentRoute: () => AdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountOrderIdRoute =
  AuthenticatedAccountOrderIdRouteImport.update({
    id: '/order/$id',
    path: '/order/$id',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AdminAdminAccountingReportsRoute =
  AdminAdminAccountingReportsRouteImport.update({
    id: '/admin/accounting/reports',
    path: '/admin/accounting/reports',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccountingPeriodsRoute =
  AdminAdminAccountingPeriodsRouteImport.update({
    id: '/admin/accounting/periods',
    path: '/admin/accounting/periods',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccountingExpensesRoute =
  AdminAdminAccountingExpensesRouteImport.update({
    id: '/admin/accounting/expenses',
    path: '/admin/accounting/expenses',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccountingCostsRoute =
  AdminAdminAccountingCostsRouteImport.update({
    id: '/admin/accounting/costs',
    path: '/admin/accounting/costs',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activation-guide': typeof ActivationGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/activation-guide': typeof AdminAdminActivationGuideRoute
  '/admin/articles': typeof AdminAdminArticlesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/api/public/edfapay-webhook': typeof ApiPublicEdfapayWebhookRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/accounting/costs': typeof AdminAdminAccountingCostsRoute
  '/admin/accounting/expenses': typeof AdminAdminAccountingExpensesRoute
  '/admin/accounting/periods': typeof AdminAdminAccountingPeriodsRoute
  '/admin/accounting/reports': typeof AdminAdminAccountingReportsRoute
  '/account/order/$id': typeof AuthenticatedAccountOrderIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activation-guide': typeof ActivationGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/activation-guide': typeof AdminAdminActivationGuideRoute
  '/admin/articles': typeof AdminAdminArticlesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/api/public/edfapay-webhook': typeof ApiPublicEdfapayWebhookRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin/accounting/costs': typeof AdminAdminAccountingCostsRoute
  '/admin/accounting/expenses': typeof AdminAdminAccountingExpensesRoute
  '/admin/accounting/periods': typeof AdminAdminAccountingPeriodsRoute
  '/admin/accounting/reports': typeof AdminAdminAccountingReportsRoute
  '/account/order/$id': typeof AuthenticatedAccountOrderIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/activation-guide': typeof ActivationGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_admin/admin/activation-guide': typeof AdminAdminActivationGuideRoute
  '/_admin/admin/articles': typeof AdminAdminArticlesRoute
  '/_admin/admin/coupons': typeof AdminAdminCouponsRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/inventory': typeof AdminAdminInventoryRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/profile': typeof AdminAdminProfileRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/api/public/edfapay-webhook': typeof ApiPublicEdfapayWebhookRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_admin/admin/accounting/costs': typeof AdminAdminAccountingCostsRoute
  '/_admin/admin/accounting/expenses': typeof AdminAdminAccountingExpensesRoute
  '/_admin/admin/accounting/periods': typeof AdminAdminAccountingPeriodsRoute
  '/_admin/admin/accounting/reports': typeof AdminAdminAccountingReportsRoute
  '/_authenticated/account/order/$id': typeof AuthenticatedAccountOrderIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activation-guide'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/products'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/track-order'
    | '/account'
    | '/admin/login'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/order-success/$id'
    | '/payment/failed'
    | '/payment/success'
    | '/product/$slug'
    | '/admin/activation-guide'
    | '/admin/articles'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/account/orders'
    | '/api/public/edfapay-webhook'
    | '/account/'
    | '/admin/accounting/costs'
    | '/admin/accounting/expenses'
    | '/admin/accounting/periods'
    | '/admin/accounting/reports'
    | '/account/order/$id'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activation-guide'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/products'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/track-order'
    | '/admin/login'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/order-success/$id'
    | '/payment/failed'
    | '/payment/success'
    | '/product/$slug'
    | '/admin/activation-guide'
    | '/admin/articles'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/account/orders'
    | '/api/public/edfapay-webhook'
    | '/account'
    | '/admin/accounting/costs'
    | '/admin/accounting/expenses'
    | '/admin/accounting/periods'
    | '/admin/accounting/reports'
    | '/account/order/$id'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/activation-guide'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/products'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/track-order'
    | '/_authenticated/account'
    | '/admin/login'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/order-success/$id'
    | '/payment/failed'
    | '/payment/success'
    | '/product/$slug'
    | '/_admin/admin/activation-guide'
    | '/_admin/admin/articles'
    | '/_admin/admin/coupons'
    | '/_admin/admin/customers'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/inventory'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/profile'
    | '/_admin/admin/reports'
    | '/_admin/admin/reviews'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_authenticated/account/orders'
    | '/api/public/edfapay-webhook'
    | '/_authenticated/account/'
    | '/_admin/admin/accounting/costs'
    | '/_admin/admin/accounting/expenses'
    | '/_admin/admin/accounting/periods'
    | '/_admin/admin/accounting/reports'
    | '/_authenticated/account/order/$id'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivationGuideRoute: typeof ActivationGuideRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  OrderSuccessIdRoute: typeof OrderSuccessIdRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicEdfapayWebhookRoute: typeof ApiPublicEdfapayWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-guide': {
      id: '/activation-guide'
      path: '/activation-guide'
      fullPath: '/activation-guide'
      preLoaderRoute: typeof ActivationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$id': {
      id: '/order-success/$id'
      path: '/order-success/$id'
      fullPath: '/order-success/$id'
      preLoaderRoute: typeof OrderSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/public/edfapay-webhook': {
      id: '/api/public/edfapay-webhook'
      path: '/api/public/edfapay-webhook'
      fullPath: '/api/public/edfapay-webhook'
      preLoaderRoute: typeof ApiPublicEdfapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reviews': {
      id: '/_admin/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/profile': {
      id: '/_admin/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory': {
      id: '/_admin/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminAdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/coupons': {
      id: '/_admin/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminAdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/articles': {
      id: '/_admin/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminAdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/activation-guide': {
      id: '/_admin/admin/activation-guide'
      path: '/admin/activation-guide'
      fullPath: '/admin/activation-guide'
      preLoaderRoute: typeof AdminAdminActivationGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/order/$id': {
      id: '/_authenticated/account/order/$id'
      path: '/order/$id'
      fullPath: '/account/order/$id'
      preLoaderRoute: typeof AuthenticatedAccountOrderIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_admin/admin/accounting/reports': {
      id: '/_admin/admin/accounting/reports'
      path: '/admin/accounting/reports'
      fullPath: '/admin/accounting/reports'
      preLoaderRoute: typeof AdminAdminAccountingReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accounting/periods': {
      id: '/_admin/admin/accounting/periods'
      path: '/admin/accounting/periods'
      fullPath: '/admin/accounting/periods'
      preLoaderRoute: typeof AdminAdminAccountingPeriodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accounting/expenses': {
      id: '/_admin/admin/accounting/expenses'
      path: '/admin/accounting/expenses'
      fullPath: '/admin/accounting/expenses'
      preLoaderRoute: typeof AdminAdminAccountingExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accounting/costs': {
      id: '/_admin/admin/accounting/costs'
      path: '/admin/accounting/costs'
      fullPath: '/admin/accounting/costs'
      preLoaderRoute: typeof AdminAdminAccountingCostsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminActivationGuideRoute: typeof AdminAdminActivationGuideRoute
  AdminAdminArticlesRoute: typeof AdminAdminArticlesRoute
  AdminAdminCouponsRoute: typeof AdminAdminCouponsRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminInventoryRoute: typeof AdminAdminInventoryRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminProfileRoute: typeof AdminAdminProfileRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminAccountingCostsRoute: typeof AdminAdminAccountingCostsRoute
  AdminAdminAccountingExpensesRoute: typeof AdminAdminAccountingExpensesRoute
  AdminAdminAccountingPeriodsRoute: typeof AdminAdminAccountingPeriodsRoute
  AdminAdminAccountingReportsRoute: typeof AdminAdminAccountingReportsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminActivationGuideRoute: AdminAdminActivationGuideRoute,
  AdminAdminArticlesRoute: AdminAdminArticlesRoute,
  AdminAdminCouponsRoute: AdminAdminCouponsRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminInventoryRoute: AdminAdminInventoryRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminProfileRoute: AdminAdminProfileRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminAccountingCostsRoute: AdminAdminAccountingCostsRoute,
  AdminAdminAccountingExpensesRoute: AdminAdminAccountingExpensesRoute,
  AdminAdminAccountingPeriodsRoute: AdminAdminAccountingPeriodsRoute,
  AdminAdminAccountingReportsRoute: AdminAdminAccountingReportsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountOrderIdRoute: typeof AuthenticatedAccountOrderIdRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountOrderIdRoute: AuthenticatedAccountOrderIdRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivationGuideRoute: ActivationGuideRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  AdminLoginRoute: AdminLoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  OrderSuccessIdRoute: OrderSuccessIdRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicEdfapayWebhookRoute: ApiPublicEdfapayWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
