// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const ACTIVE_SUPABASE_URL = "https://zvowztkpigjauvyavapl.supabase.co";
const ACTIVE_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2b3d6dGtwaWdqYXV2eWF2YXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MDk3NjgsImV4cCI6MjEwMzE4NTc2OH0.YMMzkt9zfsvEMTRLG1Ex78ms2c5NGjE3QoutSYV6C-Y";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || ACTIVE_SUPABASE_URL;
  let SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || ACTIVE_SUPABASE_KEY;

  // Protect against deprecated legacy Supabase project
  if (SUPABASE_URL.includes('gnmkfnwmvjcfomwnnlgh') || !SUPABASE_URL) {
    SUPABASE_URL = ACTIVE_SUPABASE_URL;
    SUPABASE_PUBLISHABLE_KEY = ACTIVE_SUPABASE_KEY;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
