// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const ACTIVE_SUPABASE_URL = "https://umozikpkfmjkcglizysd.supabase.co";

function getCleanUrl(): string {
  const cfEnv = (globalThis as unknown as { __CF_ENV__?: Record<string, unknown> }).__CF_ENV__;
  const envUrl =
    process.env.SUPABASE_URL ||
    process.env.VITE_SUPABASE_URL ||
    (cfEnv?.SUPABASE_URL as string | undefined) ||
    (cfEnv?.VITE_SUPABASE_URL as string | undefined);

  if (envUrl && typeof envUrl === "string" && envUrl.trim()) {
    return envUrl.trim();
  }
  return ACTIVE_SUPABASE_URL;
}

function getCleanKey(): string {
  const cfEnv = (globalThis as unknown as { __CF_ENV__?: Record<string, unknown> }).__CF_ENV__;
  const envKey =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    (cfEnv?.SUPABASE_SERVICE_ROLE_KEY as string | undefined);

  if (envKey && typeof envKey === "string" && envKey.trim()) {
    return envKey.trim();
  }
  throw new Error("SUPABASE_SERVICE_ROLE_KEY environment variable is required for server admin operations.");
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = getCleanUrl();
  const SUPABASE_SERVICE_ROLE_KEY = getCleanKey();

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
